Pmax=? [ (F h=5)&(G (!(h=1))) ]

Pmax=? [ (F h=5)&(!(h=5) U (h=1)) ]

Pmax=? [ (F h=5)&(!(h=5) U (h=2)) ]

Pmax=? [ (F h=5) ]

Pmax=? [ (F h=5)&(G (!(h=2))) ]

Pmax=? [ (F h=5)&(G (!(h=7))) ]

Pmax=? [ (F h=5)&(!(h=5) U (h=7)) ]

Pmax=? [ (F h=5) & (X (h=1&(X (h=3)))) ]

E [ X (h=1&(X (h=2))) ]

Pmax=? [ X (h=1&(X (h=3&(X (h=5)))))]

Pmax=? [ (F h=5) & (!(h=5) U (X (h=1&(X (h=3&(X (h=5))))))) ]

multi (Pmax=? [ (F h=5)&(G (!(h=1))) ], Pmax=? [ (F h=7)&(G (!(h=1))) ] )